// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0dd600FTnFdmf97T04pyWCdcofO0gu2s',
    appId: '1:361539604503:web:289f154039055d08c58c52',
    messagingSenderId: '361539604503',
    projectId: 'socia-2591f',
    authDomain: 'socia-2591f.firebaseapp.com',
    storageBucket: 'socia-2591f.firebasestorage.app',
    measurementId: 'G-682L0LGHWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHiRhNOYQkaEPXNMki_C0U-NZFv8O2X_E',
    appId: '1:361539604503:android:316cf09512dedd94c58c52',
    messagingSenderId: '361539604503',
    projectId: 'socia-2591f',
    storageBucket: 'socia-2591f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChpFue-L7dVphDQxwnst_LU9_d7uiMjwc',
    appId: '1:361539604503:ios:c7694f8c665e5323c58c52',
    messagingSenderId: '361539604503',
    projectId: 'socia-2591f',
    storageBucket: 'socia-2591f.firebasestorage.app',
    iosBundleId: 'com.example.projectSociaMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChpFue-L7dVphDQxwnst_LU9_d7uiMjwc',
    appId: '1:361539604503:ios:c7694f8c665e5323c58c52',
    messagingSenderId: '361539604503',
    projectId: 'socia-2591f',
    storageBucket: 'socia-2591f.firebasestorage.app',
    iosBundleId: 'com.example.projectSociaMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0dd600FTnFdmf97T04pyWCdcofO0gu2s',
    appId: '1:361539604503:web:846d6b6e6e743fb2c58c52',
    messagingSenderId: '361539604503',
    projectId: 'socia-2591f',
    authDomain: 'socia-2591f.firebaseapp.com',
    storageBucket: 'socia-2591f.firebasestorage.app',
    measurementId: 'G-DW7FGTQ0XV',
  );
}
